project_name: ts-node-express
project_description: 'TypeScript Node Starter Project'
repository_url: 'https://github.com/kabirbaidhya/ts-node-express'
branch_url: '{repository_url}/tree/{branch}'
port: 3022
ssh_forward_agent: true
verbose_logging: false
remote_env_injection: true
remote_env_path: '~/test/app.env'

deployment:
  preset: node
  base_dir: /home/app/deployment
  include_files: ['package.json', 'package-lock.json', 'yarn.lock', 'pm2.config.js']

stages:
  foo:
    host: foobar.localhost

scripts:
  logs: 'pm2 logs'
  status_check: 'pm2 info api'
  start: 'pm2 startOrReload current/pm2.config.js'
  stop: 'pm2 stop current/pm2.config.js'
  reload: 'pm2 reload current/rm2.config.js'
  list_services: 'pm2 list current/pm2.config.js'

notifications:
  slack:
    enabled: true
    endpoint: /T1JUS2Q2V/B4ULRGFBN/SbS6YY7FcYU1gabDct5hBxkw

